import type { Metadata } from "next";
import Link from "next/link";
import './globals.css';
import Options from "./components/options";

interface Topic {
  id: string;
  title: string;
  body: string;
}

export const metadata: Metadata = {
  title: "Web tutorials",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch(`${process.env.BASE_URL}`, { cache: "no-store" });
  const topics: Topic[] = await res.json();
  return (
    <html lang="en">
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map(topic => <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>)}
        </ol>
        {children}
        <Options/>
      </body>
    </html>
  );
}
